name: Build

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.1"
          cache-dependency-path: event-simulator/go.mod

      - name: Go Vet
        run: go vet ./...
        working-directory: event-simulator

      - name: Test
        run: go test ./...
        working-directory: event-simulator

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/incident-reactor
          tags: |
            type=sha
            type=ref,event=branch

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: event-simulator
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.35.3"

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region us-east-2 \
            --name incident-reactor

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8/

      - name: Deploy new image
        run: |
          IMAGE=${{ steps.login-ecr.outputs.registry }}/incident-reactor:sha-${GITHUB_SHA::7}

          kubectl set image deployment/incident-reactor \
            app=$IMAGE

          kubectl rollout status deployment/incident-reactor
